// Test generated by RoostGPT for test React_Test using AI Type Open AI and AI Model gpt-4

import { validateEmail } from './Login';

describe('Email Validation', () => {
  test('validates correct email', () => {
    const email = 'test@example.com';
    const result = validateEmail(email);
    expect(result).toBe(true);
  });

  test('invalidates incorrect email', () => {
    const email = 'invalid_email';
    const result = validateEmail(email);
    expect(result).toBe(false);
  });

  test('invalidates email without domain', () => {
    const email = 'test@';
    const result = validateEmail(email);
    expect(result).toBe(false);
  });

  test('invalidates email without @ symbol', () => {
    const email = 'test.example.com';
    const result = validateEmail(email);
    expect(result).toBe(false);
  });

  test('invalidates email with spaces', () => {
    const email = 'test @example.com';
    const result = validateEmail(email);
    expect(result).toBe(false);
  });
});
