// Test generated by RoostGPT for test React_Test using AI Type Open AI and AI Model gpt-4

import { validateEmail } from './Login';

describe('Email validation', () => {
  test('Valid email', () => {
    expect(validateEmail('test@example.com')).toBe(true);
  });

  test('Email without @', () => {
    expect(validateEmail('test.example.com')).toBe(false);
  });

  test('Email without .', () => {
    expect(validateEmail('test@examplecom')).toBe(false);
  });

  test('Email with space', () => {
    expect(validateEmail('test @example.com')).toBe(false);
  });

  test('Email with less than 2 characters in domain extension', () => {
    expect(validateEmail('test@example.c')).toBe(false);
  });

  test('Empty email', () => {
    expect(validateEmail('')).toBe(false);
  });
});
