// Test generated by RoostGPT for test React_Test using AI Type Open AI and AI Model gpt-4

import { validateEmail } from './Login';

describe('Email Validation', () => {
  test('validates email correctly', () => {
    expect(validateEmail('test@test.com')).toBe(true);
  });

  test('returns false for invalid email', () => {
    expect(validateEmail('test@test')).toBe(false);
  });

  test('returns false for email without @ symbol', () => {
    expect(validateEmail('test.com')).toBe(false);
  });

  test('returns false for email without .com (or any extension)', () => {
    expect(validateEmail('test@test')).toBe(false);
  });

  test('returns false for email with spaces', () => {
    expect(validateEmail('test @test.com')).toBe(false);
  });
});
