// Test generated by RoostGPT for test React_Test using AI Type Open AI and AI Model gpt-4

import React from 'react';
import { render } from '@testing-library/react';
import App from './App';
import Login from './components/Login';

describe('App Component', () => {
  beforeEach(() => {
    render(<App />);
  });

  test('renders App component', () => {
    const appComponent = document.querySelector('.app-container');
    expect(appComponent).toBeInTheDocument();
  });

  test('renders header text', () => {
    const header = document.querySelector('h1');
    expect(header).toBeInTheDocument();
    expect(header.textContent).toBe('This is React Testing Tutorial');
  });

  test('renders Login component', () => {
    const loginComponent = document.querySelector('[data-testid="child"]');
    expect(loginComponent).toBeInTheDocument();
  });
});
