// Test generated by RoostGPT for test React_Test using AI Type Open AI and AI Model gpt-4

import "@testing-library/jest-dom";
import "@testing-library/jest-dom";

describe('afterAll method test suite', () => {
  let originalError;

  beforeAll(() => {
    originalError = console.error;
  });

  test('should restore original console error after all tests', () => {
    console.error = jest.fn();
    expect(console.error).not.toBe(originalError);
    afterAll(() => {
      console.error = originalError;
    });
    expect(console.error).toBe(originalError);
  });

  test('should not change console error if it was not mocked', () => {
    const initialConsoleError = console.error;
    afterAll(() => {
      console.error = originalError;
    });
    expect(console.error).toBe(initialConsoleError);
  });
});
