// Test generated by RoostGPT for test React_Test using AI Type Open AI and AI Model gpt-4

import "@testing-library/jest-dom";
import "@testing-library/jest-dom";

// Mock console.error
let originalError;
beforeAll(() => {
  originalError = console.error;
  console.error = jest.fn();
});

describe("AfterAll method", () => {

  test("console.error is called", () => {
    console.error('Test error');
    expect(console.error).toHaveBeenCalledWith('Test error');
  });

  test("console.error is not called", () => {
    expect(console.error).not.toHaveBeenCalled();
  });

});

afterAll(() => {
  console.error = originalError;
});
