// Test generated by RoostGPT for test React_Test using AI Type Open AI and AI Model gpt-4

import "@testing-library/jest-dom";
import "@testing-library/jest-dom";

describe('Test afterAll function', () => {
  let originalError;
  let consoleSpy;

  beforeAll(() => {
    originalError = console.error;
    consoleSpy = jest.spyOn(console, 'error').mockImplementation(() => {});
  })

  afterAll(() => {
    console.error = originalError;
  })

  test('console.error should be called', () => {
    console.error('Test error');
    expect(consoleSpy).toHaveBeenCalled();
  })

  test('console.error should not be called', () => {
    expect(consoleSpy).not.toHaveBeenCalled();
  })

  test('console.error should be restored to original function after all tests', () => {
    expect(console.error).toBe(originalError);
  })
})
