// Test generated by RoostGPT for test React_Test using AI Type Open AI and AI Model gpt-4

import "@testing-library/jest-dom";

describe('Console error method', () => {
    let originalError;

    beforeAll(() => {
        originalError = console.error;
    });

    afterEach(() => {
        console.error = originalError;
    });

    test('should not call original console.error for React 18 warning', () => {
        const mockError = jest.fn();
        console.error = mockError;

        console.error('Warning: ReactDOM.render is no longer supported in React 18.');

        expect(mockError).not.toHaveBeenCalled();
    });

    test('should call original console.error for other messages', () => {
        const mockError = jest.fn();
        console.error = mockError;

        console.error('An unrelated error message.');

        expect(mockError).toHaveBeenCalled();
    });
});
