// Test generated by RoostGPT for test React_Test using AI Type Open AI and AI Model gpt-4

import "@testing-library/jest-dom";

describe('console.error override', () => {
  let originalError;

  beforeAll(() => {
    originalError = console.error;
  });

  afterAll(() => {
    console.error = originalError;
  });

  test('should silence specific React 18 warning', () => {
    const warningMessage = 'Warning: ReactDOM.render is no longer supported in React 18.';
    console.error = (...args) => {
      if (/Warning: ReactDOM.render is no longer supported in React 18./.test(args[0])) {
        return;
      }
      originalError.call(console, ...args);
    };
    console.error(warningMessage);
    expect(originalError).not.toHaveBeenCalled();
  });

  test('should not silence other console errors', () => {
    const errorMessage = 'An error occurred';
    console.error = (...args) => {
      if (/Warning: ReactDOM.render is no longer supported in React 18./.test(args[0])) {
        return;
      }
      originalError.call(console, ...args);
    };
    console.error(errorMessage);
    expect(originalError).toHaveBeenCalledWith(errorMessage);
  });
});
