// Test generated by RoostGPT for test React_Test using AI Type Open AI and AI Model gpt-4

import "@testing-library/jest-dom";
import originalError from './setupTests';

describe('console error', () => {
  let originalConsoleError;

  beforeAll(() => {
    originalConsoleError = console.error;
  });

  afterEach(() => {
    console.error = originalConsoleError;
  });

  test('console.error does not log ReactDOM.render warning', () => {
    console.error = (...args) => {
      if (/Warning: ReactDOM.render is no longer supported in React 18./.test(args[0])) {
        return;
      }
      originalError.call(console, ...args);
    };

    console.error('Warning: ReactDOM.render is no longer supported in React 18.');
    expect(originalError).not.toBeCalled();
  });

  test('console.error logs non ReactDOM.render warnings', () => {
    console.error = (...args) => {
      if (/Warning: ReactDOM.render is no longer supported in React 18./.test(args[0])) {
        return;
      }
      originalError.call(console, ...args);
    };

    console.error('Warning: This is a test warning');
    expect(originalError).toBeCalledWith('Warning: This is a test warning');
  });
});
