// Test generated by RoostGPT for test React_Test using AI Type Open AI and AI Model gpt-4

const reportWebVitals = require('./reportWebVitals');

describe('reportWebVitals', () => {
    let onPerfEntry;

    beforeEach(() => {
        onPerfEntry = jest.fn();
        jest.mock('web-vitals', () => ({
            getCLS: jest.fn().mockImplementation((cb) => cb()),
            getFID: jest.fn().mockImplementation((cb) => cb()),
            getFCP: jest.fn().mockImplementation((cb) => cb()),
            getLCP: jest.fn().mockImplementation((cb) => cb()),
            getTTFB: jest.fn().mockImplementation((cb) => cb()),
        }));
    });

    afterEach(() => {
        jest.resetAllMocks();
    });

    test('should not call onPerfEntry when it is not a function', () => {
        reportWebVitals(null);
        expect(onPerfEntry).not.toHaveBeenCalled();
    });

    test('should call onPerfEntry for each web vital when it is a function', () => {
        reportWebVitals(onPerfEntry);
        expect(onPerfEntry).toHaveBeenCalledTimes(5);
    });
});
