// Test generated by RoostGPT for test React_Test using AI Type Open AI and AI Model gpt-4

const reportWebVitals = require('./reportWebVitals');

describe('reportWebVitals', () => {
  let onPerfEntry;
  let getCLS, getFID, getFCP, getLCP, getTTFB;

  beforeEach(() => {
    onPerfEntry = jest.fn();

    getCLS = jest.fn();
    getFID = jest.fn();
    getFCP = jest.fn();
    getLCP = jest.fn();
    getTTFB = jest.fn();

    jest.mock('web-vitals', () => ({
      getCLS,
      getFID,
      getFCP,
      getLCP,
      getTTFB
    }));
  });

  test('should not call any function when onPerfEntry is not a function', () => {
    reportWebVitals(null);
    expect(onPerfEntry).not.toHaveBeenCalled();
    expect(getCLS).not.toHaveBeenCalled();
    expect(getFID).not.toHaveBeenCalled();
    expect(getFCP).not.toHaveBeenCalled();
    expect(getLCP).not.toHaveBeenCalled();
    expect(getTTFB).not.toHaveBeenCalled();
  });

  test('should call onPerfEntry and all web-vitals methods when onPerfEntry is a function', async () => {
    await reportWebVitals(onPerfEntry);
    expect(onPerfEntry).toHaveBeenCalled();
    expect(getCLS).toHaveBeenCalled();
    expect(getFID).toHaveBeenCalled();
    expect(getFCP).toHaveBeenCalled();
    expect(getLCP).toHaveBeenCalled();
    expect(getTTFB).toHaveBeenCalled();
  });
});
